name: Auto Label Repo Requests

on:
  issues:
    types: [opened]

jobs:
  add-label-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add pending label and comment
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            // Add 'pending' label
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['pending']
            });

            // Post comment
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `👋 Thanks for your repository request! The team will review it shortly. If approved, you’ll be notified here.`
            });
